### ISSUE TITLE
Buffer of execution gets opened in other window

### ISSUE THREAD

**Issue by jsab** [linktohack/ob-async#1]
If you switch windows during the asynchronous execution of the babel block. When the execution complete, the buffer of the window you are in will switch to the buffer of the execution..

Reproduction steps:
1. Split frame in two windows.
2. Put org buffer in one window, another unrelated buffer in the other
3. Execute a code block in the first window and immediately switch to the other
4. When execution completes your second window will open the org buffer.

**Comment by linktohack** [comment]
Thanks @jsab , I will have a look this weekend

**Comment by linktohack** [comment]
Hi @jsab , I am unable to reproduce this, can you please try again with a minimal `init.el`?

http://imgur.com/a/bduNg

**Comment by jsab** [comment]
Do you get a `Mark set` message upon completion? i.e.:

````
Evaluate this http code block on your system? (y or n) y
executing Http code block...
Code block evaluation complete.
Mark set
````

Basically, I'm using spacemacs so far from a minimal config but probably a very common config. Do you have a minimal `init.el` I could test with?

**Comment by linktohack** [comment]
Please edit the first two lines to match your case, if you are using default `init.el`, just delete them.

```emacs-lisp
(setq user-init-file "~/Downloads/1.el"
      user-emacs-directory "~/.emacs.me.d/")
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")
                         ("org" . "http://orgmode.org/elpa/"))
      package-enable-at-startup nil)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(use-package async :ensure :demand
  :init (setq async-bytecomp-allowed-packages '(all))
  :config (async-bytecomp-package-mode 1))

(use-package org :defer
  :load-path "~/Dropbox/ProjectWeekends/lisp/ob-async/"
  :config
  (require 'ob)
  (require 'ob-async)
  (setq org-confirm-babel-evaluate nil
        org-export-babel-evaluate 'inline-only)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t) (org . t)
     (shell . t) (makefile . t)
     (latex . t)
     (fortran . t) (gnuplot . t) (python . t))))
```

**Comment by linktohack** [comment]
Cleaning up, feel free to reopen if you're still having problems...
